/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidatorsRouteImport } from './routes/validators'
import { Route as UptimeRouteImport } from './routes/uptime'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StateSyncRouteImport } from './routes/state-sync'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ParametersRouteImport } from './routes/parameters'
import { Route as IbcTransferRouteImport } from './routes/ibc-transfer'
import { Route as GlobeRouteImport } from './routes/globe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CosmwasmRouteImport } from './routes/cosmwasm'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidatorsAddressRouteImport } from './routes/validators.$address'
import { Route as TransactionsHashRouteImport } from './routes/transactions.$hash'
import { Route as ProposalsIdRouteImport } from './routes/proposals.$id'
import { Route as BlocksHeightRouteImport } from './routes/blocks.$height'
import { Route as AccountsAddressRouteImport } from './routes/accounts.$address'

const ValidatorsRoute = ValidatorsRouteImport.update({
  id: '/validators',
  path: '/validators',
  getParentRoute: () => rootRouteImport,
} as any)
const UptimeRoute = UptimeRouteImport.update({
  id: '/uptime',
  path: '/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StateSyncRoute = StateSyncRouteImport.update({
  id: '/state-sync',
  path: '/state-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersRoute = ParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const IbcTransferRoute = IbcTransferRouteImport.update({
  id: '/ibc-transfer',
  path: '/ibc-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobeRoute = GlobeRouteImport.update({
  id: '/globe',
  path: '/globe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmwasmRoute = CosmwasmRouteImport.update({
  id: '/cosmwasm',
  path: '/cosmwasm',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsAddressRoute = ValidatorsAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => ValidatorsRoute,
} as any)
const TransactionsHashRoute = TransactionsHashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => TransactionsRoute,
} as any)
const ProposalsIdRoute = ProposalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProposalsRoute,
} as any)
const BlocksHeightRoute = BlocksHeightRouteImport.update({
  id: '/$height',
  path: '/$height',
  getParentRoute: () => BlocksRoute,
} as any)
const AccountsAddressRoute = AccountsAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => AccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/cosmwasm': typeof CosmwasmRoute
  '/dashboard': typeof DashboardRoute
  '/globe': typeof GlobeRoute
  '/ibc-transfer': typeof IbcTransferRoute
  '/parameters': typeof ParametersRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/state-sync': typeof StateSyncRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/uptime': typeof UptimeRoute
  '/validators': typeof ValidatorsRouteWithChildren
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/validators/$address': typeof ValidatorsAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/cosmwasm': typeof CosmwasmRoute
  '/dashboard': typeof DashboardRoute
  '/globe': typeof GlobeRoute
  '/ibc-transfer': typeof IbcTransferRoute
  '/parameters': typeof ParametersRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/state-sync': typeof StateSyncRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/uptime': typeof UptimeRoute
  '/validators': typeof ValidatorsRouteWithChildren
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/validators/$address': typeof ValidatorsAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/cosmwasm': typeof CosmwasmRoute
  '/dashboard': typeof DashboardRoute
  '/globe': typeof GlobeRoute
  '/ibc-transfer': typeof IbcTransferRoute
  '/parameters': typeof ParametersRoute
  '/proposals': typeof ProposalsRouteWithChildren
  '/state-sync': typeof StateSyncRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/uptime': typeof UptimeRoute
  '/validators': typeof ValidatorsRouteWithChildren
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/proposals/$id': typeof ProposalsIdRoute
  '/transactions/$hash': typeof TransactionsHashRoute
  '/validators/$address': typeof ValidatorsAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/blocks'
    | '/cosmwasm'
    | '/dashboard'
    | '/globe'
    | '/ibc-transfer'
    | '/parameters'
    | '/proposals'
    | '/state-sync'
    | '/transactions'
    | '/uptime'
    | '/validators'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/proposals/$id'
    | '/transactions/$hash'
    | '/validators/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/blocks'
    | '/cosmwasm'
    | '/dashboard'
    | '/globe'
    | '/ibc-transfer'
    | '/parameters'
    | '/proposals'
    | '/state-sync'
    | '/transactions'
    | '/uptime'
    | '/validators'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/proposals/$id'
    | '/transactions/$hash'
    | '/validators/$address'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/blocks'
    | '/cosmwasm'
    | '/dashboard'
    | '/globe'
    | '/ibc-transfer'
    | '/parameters'
    | '/proposals'
    | '/state-sync'
    | '/transactions'
    | '/uptime'
    | '/validators'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/proposals/$id'
    | '/transactions/$hash'
    | '/validators/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  BlocksRoute: typeof BlocksRouteWithChildren
  CosmwasmRoute: typeof CosmwasmRoute
  DashboardRoute: typeof DashboardRoute
  GlobeRoute: typeof GlobeRoute
  IbcTransferRoute: typeof IbcTransferRoute
  ParametersRoute: typeof ParametersRoute
  ProposalsRoute: typeof ProposalsRouteWithChildren
  StateSyncRoute: typeof StateSyncRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
  UptimeRoute: typeof UptimeRoute
  ValidatorsRoute: typeof ValidatorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validators': {
      id: '/validators'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uptime': {
      id: '/uptime'
      path: '/uptime'
      fullPath: '/uptime'
      preLoaderRoute: typeof UptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state-sync': {
      id: '/state-sync'
      path: '/state-sync'
      fullPath: '/state-sync'
      preLoaderRoute: typeof StateSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters': {
      id: '/parameters'
      path: '/parameters'
      fullPath: '/parameters'
      preLoaderRoute: typeof ParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ibc-transfer': {
      id: '/ibc-transfer'
      path: '/ibc-transfer'
      fullPath: '/ibc-transfer'
      preLoaderRoute: typeof IbcTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globe': {
      id: '/globe'
      path: '/globe'
      fullPath: '/globe'
      preLoaderRoute: typeof GlobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmwasm': {
      id: '/cosmwasm'
      path: '/cosmwasm'
      fullPath: '/cosmwasm'
      preLoaderRoute: typeof CosmwasmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/$address': {
      id: '/validators/$address'
      path: '/$address'
      fullPath: '/validators/$address'
      preLoaderRoute: typeof ValidatorsAddressRouteImport
      parentRoute: typeof ValidatorsRoute
    }
    '/transactions/$hash': {
      id: '/transactions/$hash'
      path: '/$hash'
      fullPath: '/transactions/$hash'
      preLoaderRoute: typeof TransactionsHashRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/proposals/$id': {
      id: '/proposals/$id'
      path: '/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof ProposalsIdRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/blocks/$height': {
      id: '/blocks/$height'
      path: '/$height'
      fullPath: '/blocks/$height'
      preLoaderRoute: typeof BlocksHeightRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/accounts/$address': {
      id: '/accounts/$address'
      path: '/$address'
      fullPath: '/accounts/$address'
      preLoaderRoute: typeof AccountsAddressRouteImport
      parentRoute: typeof AccountsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsAddressRoute: typeof AccountsAddressRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAddressRoute: AccountsAddressRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface BlocksRouteChildren {
  BlocksHeightRoute: typeof BlocksHeightRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksHeightRoute: BlocksHeightRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface ProposalsRouteChildren {
  ProposalsIdRoute: typeof ProposalsIdRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsIdRoute: ProposalsIdRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsHashRoute: typeof TransactionsHashRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsHashRoute: TransactionsHashRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

interface ValidatorsRouteChildren {
  ValidatorsAddressRoute: typeof ValidatorsAddressRoute
}

const ValidatorsRouteChildren: ValidatorsRouteChildren = {
  ValidatorsAddressRoute: ValidatorsAddressRoute,
}

const ValidatorsRouteWithChildren = ValidatorsRoute._addFileChildren(
  ValidatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  BlocksRoute: BlocksRouteWithChildren,
  CosmwasmRoute: CosmwasmRoute,
  DashboardRoute: DashboardRoute,
  GlobeRoute: GlobeRoute,
  IbcTransferRoute: IbcTransferRoute,
  ParametersRoute: ParametersRoute,
  ProposalsRoute: ProposalsRouteWithChildren,
  StateSyncRoute: StateSyncRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
  UptimeRoute: UptimeRoute,
  ValidatorsRoute: ValidatorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
